image: node:14

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build

deploy:
  stage: deploy
  dependencies: build
  script:
    - cp build $HOME/drp-client-web-build
