image: node:14

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build

deploy-staging:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -r $HOME/drp-client-web-build
    - cp -r build $HOME/drp-client-web-build
  only:
    - master
  tags:
    - deploy-staging
