name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload built app
        uses: actions/upload-artifact@v2
        with:
          name: drp-client-web
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Publish docker image
        uses: docker/build-push-action@v1
        with:
          repository: hasali19/drp-client-web
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          tag_with_sha: true
